// Shared, server-independent UI pieces (reused by the ops app and the demo).
export { FleetMap } from "./FleetMap.js";
export type { MapMarker, RobotDot } from "./FleetMap.js";
export { defaultActionLabel, runningAction } from "./actions.js";
export { default as App, Shell } from "./App.js";
export { POSE_TTL_MS, RobotCards, buildCards, filterCards, pruneStalePoses, summarizeCards } from "./RobotCards.js";
export type { FleetFilter, RobotCardModel } from "./RobotCards.js";
export { TaskHistory, outcomeColor, selectHistory } from "./TaskHistory.js";
export type { HistoryFilter } from "./TaskHistory.js";
export { TaskBoard } from "./TaskBoard.js";
export { DemandBoard, zoneRows } from "./DemandBoard.js";
export type { ZoneRow } from "./DemandBoard.js";
export { ToastProvider, toastReducer, useToast } from "./Toast.js";
export type { Toast, ToastAction, ToastKind } from "./Toast.js";
export { ConfirmProvider, useConfirm } from "./Confirm.js";
export type { ConfirmRequest } from "./Confirm.js";
export { MobileShell } from "./MobileShell.js";
export type { MobileShellProps } from "./MobileShell.js";
export { useFleetSite } from "./useFleetSite.js";
export type { FleetSiteData } from "./useFleetSite.js";
export { NARROW_BREAKPOINT_PX, shellColumns, touchStyle, useNarrow } from "./responsive.js";
export { hashFor, parseHash, useHashRoute } from "./routes.js";
export type { Route } from "./routes.js";
export { OfflineBanner, useOnline } from "./online.js";
export { robotStatus, statusColor, theme } from "./theme.js";
export type { RobotSnapshot, RobotStatus } from "./theme.js";
export { createHttpBackend } from "./backend.js";
export type { Backend, ConnectionView, DispatchInput, DispatchWaypoint, EventSourceFactory, HistoryView, LiveAction, LivePose, OrderView, Unsubscribe } from "./backend.js";
export { boundsOf, gridLines, gridSpacing, groupByZone, headingVector, indexNodes, laneShift, scaleBarLength, stationPoses, toSvg, underlayRect, viewBoxFor, zoneColor } from "./map.js";
export type { Bounds } from "./map.js";
